name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # Set your main branch name here

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install npm packages
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to AWS S3
        run: |
          aws s3 sync ./dist s3://ertitech.com --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
